minVersion: "0.34.1"
github:
  owner: getsentry
  repo: symbolic
changelogPolicy: auto

statusProvider:
  name: github
artifactProvider:
  name: github

preReleaseCommand: bash scripts/bump-version
targets:
  - name: crates
  - name: github
requireNames:
  - /^symbolic-.*.zip$/
